Jade.Shell/Areas/Api/Controllers/OrderController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com r
*

*
********************************************************************/


using AutoMapper;
using Jade.Core;
using Jade.Model;
using Jade.Model.Dto;
using Sheng.Web.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jade.Shell.Areas.Api.Controllers
{
    public class OrderController : ApiBaseController
    {
        private static readonly OrderManager _orderManager = OrderManager.Instance;

        public ActionResult GetOrder(string id)
        {
            Product_Order_Master order = _orderManager.GetOrder(id);
            if (order == null)
            {
                return FailedResult("指定的数据不存在。");
            }

            Product_Order_MasterDto orderDto = Mapper.Map<Product_Order_MasterDto>(order);
            return DataResult(orderDto);
        }

        public ActionResult RemoveOrder(string id)
        {
            _orderManager.RemoveOrder(id);
            return SuccessfulResult();
        }

        public ActionResult GetOrderList()
        {
            GetListDataArgs args = RequestArgs<GetListDataArgs>();
            if (args == null)
            {
                return FailedResult("参数无效。");
            }

            GetListDataResult<Product_Order_Master> orderList = _orderManager.GetOrderList(args);

            GetListDataResult<Product_Order_MasterInListDto> result = new GetListDataResult<Product_Order_MasterInListDto>();
            result.PagingInfo = orderList.PagingInfo;
            result.Data = Mapper.Map<List<Product_Order_Master>, List<Product_Order_MasterInListDto>>(orderList.Data);

            return DataResult(result);
        }

        public ActionResult CreateOrderRecord()
        {
            CreateOrderRecordArgs args = RequestArgs<CreateOrderRecordArgs>();
            if (args == null)
            {
                return FailedResult("参数无效。");
            }

            args.modify_user_id = this.UserContext.User.id;

            NormalResult result = _orderManager.CreateOrderRecord(args);
            return ApiResult(result.Successful, result.Message);
        }
    }
}

Jade.Shell/Controllers/MicroClassController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com r
*

*
********************************************************************/


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jade.Shell.Controllers
{
    public class MicroClassController : ShellBaseController
    {
        public ActionResult Group()
        {
            return View();
        }

        public ActionResult GroupEdit()
        {
            return View();
        }

        public ActionResult Class()
        {
            return View();
        }

        public ActionResult ClassEdit()
        {
            return View();
        }
    }
}

Jade.Shell/Controllers/PersonalCenterController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com r
*

*
********************************************************************/


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jade.Shell.Controllers
{
    public class PersonalCenterController : ShellBaseController
    {
        public ActionResult Password()
        {
            return View();
        }
    }
}

Jade.Shell/Controllers/SettingsController.cs
/*
********************************************************************
*
*    曹旭升（sheng.c）
*    E-mail: cao.silhouette@msn.com
*    QQ: 279060597
*    https://github.com/iccb1013
*    http://shengxunwei.com r
*

*
********************************************************************/


using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Jade.Shell.Controllers
{
    public class SettingsController : ShellBaseController
    {
        public new ActionResult User()
        {
            return View();
        }

        public ActionResult UserEdit()
        {
            return View();
        }

        public ActionResult MultipleUserSelector()
        {
            return View();
        }

        public ActionResult Role()
        {
            return View();
        }

        public ActionResult RoleEdit()
        {
            return View();
        }

        public ActionResult RoleUser()
        {
            return View();
        }
    }
}

Jade.Shell/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Scripts/jqueryui/jquery-ui.css")*@

    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/validate/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/layer/layer.js")
    @Scripts.Render("~/Scripts/laytpl.js")
    @Scripts.Render("~/Scripts/laypage/laypage.js")
    @Scripts.Render("~/Scripts/laydate/laydate.js")
    @Scripts.Render("~/Scripts/math.js")
    @*@Scripts.Render("~/Scripts/jqueryui/jquery-ui.js")*@

    @Styles.Render("~/Scripts/select2/css/select2.min.css")
    @Scripts.Render("~/Scripts/select2/js/select2.min.js")


    @Styles.Render("~/Scripts/layui/css/layui.css")
    @Scripts.Render("~/Scripts/layui/layui.all.js")


    @Scripts.Render("~/Scripts/layout.js")

    <style>
        body, html {
           background:#E9EBEB;
        }

      
    </style>

    <script type="text/javascript">
       
        $(document).ready(function () {

            activeLeftMenuItem("leftMenuItem_@ViewBag.SubLeftMenu");

            onReady();
        });
        
        function onReady() {

        }

    </script>

</head>
<body>
    <div class="header-wrap">
        <div class="header-wrap-inner">
            <div style="float:left;color:white;line-height:35px;font-size:18px;cursor:pointer" onclick="goUrl('/Home/PersonalCenter')">
                张寿宴玉雕工作室 2.0
            </div>
            <ul class="user-op">
                <li><a href="#">@ViewBag.UserContext.User.name</a><span>|</span></li>
                <li><a href="/Home/Logout">退出</a></li>
            </ul>
        </div>
    </div>
    <div class="header-nav-wrap">
        <div class="header-nav-wrap-inner">
            <ul>
                @if (AuthorizationHelper.Verify("L1_Settings", HttpContext.Current))
                {
                    <li><a href="@Url.Action("User","Settings")" class="@if(ViewBag.MainMenu == "Settings"){@Html.Raw("active")}">系统管理</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Member", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Member", "Member")" class="@if(ViewBag.MainMenu == "Member"){@Html.Raw("active")}">会员管理</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Product", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Product", "Product")" class="@if(ViewBag.MainMenu == "Product"){@Html.Raw("active")}">商品管理</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_MicroClass", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Group","MicroClass")" class="@if(ViewBag.MainMenu == "MicroClass"){@Html.Raw("active")}">课程管理</a></li>
                }
                <li><a href="@Url.Action("Password","PersonalCenter")" class="@if(ViewBag.MainMenu == "PersonalCenter"){@Html.Raw("active")}">个人中心</a></li>
            </ul>
        </div>
    </div>

    <div class="page-container-wrap">
        <div class="page-container-wrap-inner" style="width: 1082px;">
            <div class="nav-wrap">
                @Html.Partial("_LeftMenu")
            </div>
            <div class="main" style="">

                @RenderBody()

            </div>
        </div>
        <div class="footer-wrap">
            <p>张寿宴玉雕工作室</p>
        </div>
    </div>


</body>
</html>

Jade.Shell/Views/Shared/_LayoutBlank.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/common")

    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/validate/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/layer/layer.js")
    @Scripts.Render("~/Scripts/laytpl.js")
    @Scripts.Render("~/Scripts/laypage/laypage.js")
    @Scripts.Render("~/Scripts/laydate/laydate.js")
    @Scripts.Render("~/Scripts/math.js")

    @Styles.Render("~/Scripts/select2/css/select2.min.css")
    @Scripts.Render("~/Scripts/select2/js/select2.min.js")

    @Styles.Render("~/Scripts/layui/css/layui.css")
    @Scripts.Render("~/Scripts/layui/layui.all.js")


    <script type="text/javascript">
        // 验证值小数位数不能超过两位
        jQuery.validator.addMethod("cash", function (value, element) {
            var decimal = /^-?\d+(\.\d{1,2})?$/;
            return this.optional(element) || (decimal.test(value));
        }, $.validator.format("金额的小数位数不能超过两位；"));


        jQuery.validator.addMethod("cellphone", function (value, element) {
            if (value.length > 0 && value.length != 11)
                return false;

            var mobile = /^(((13[0-9]{1})|(15[0-9]{1})|(17[0-9]{1})|(18[0-9]{1}))+\d{8})$/;
            return this.optional(element) || (mobile.test(value));

        }, "请正确填写手机号码；");

    </script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Jade.Shell/Views/Shared/_LayoutNormalListView2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Scripts/jqueryui/jquery-ui.css")*@

    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/validate/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/layer/layer.js")
    @Scripts.Render("~/Scripts/laytpl.js")
    @Scripts.Render("~/Scripts/laypage/laypage.js")
    @Scripts.Render("~/Scripts/laydate/laydate.js")
    @Scripts.Render("~/Scripts/math.js")
    @*@Scripts.Render("~/Scripts/jqueryui/jquery-ui.js")*@

    @Styles.Render("~/Scripts/select2/css/select2.min.css")
    @Scripts.Render("~/Scripts/select2/js/select2.min.js")

    @Styles.Render("~/Scripts/layui/css/layui.css")
    @Scripts.Render("~/Scripts/layui/layui.all.js")

    @Scripts.Render("~/Scripts/listViewCommon2.js")

    @Scripts.Render("~/Scripts/layout.js")

    <style>
      
         body, html {
           background:#E9EBEB;
        }

    </style>

    <script type="text/javascript">

        $(document).ready(function () {

            activeLeftMenuItem("leftMenuItem_@ViewBag.SubLeftMenu");

            initTable();

            $("[keyenter]").keypress(function (e) {
                if (e.keyCode == 13) {
                    loadData();
                }
            });

            onReady();

            loadData();

        });

        function onReady() {

        }

        ////// 加载数据用

        function loadData(targetPage) {

            var loadListDataArgs = new Object();
            loadListDataArgs.Args = getLoadDataArgs(targetPage);
            loadListDataArgs.ApiUrl = "@ViewBag.LoadDataApiUrl";

            __loadListData(loadListDataArgs);
        }

        function create() {

            if (isExitsFunction("createOverride")) {
                createOverride();
            }
            else {

                var url = '@ViewBag.EditView';

                if (isExitsFunction("getCreateViewUrl")) {
                    url = getCreateViewUrl();
                }

                layer.open({
                    type: 2,
                    area: ['@ViewBag.EditViewAreaWidth', '@ViewBag.EditViewAreaHeight'],
                    closeBtn: false,
                    title: "",
                    shift: _layerShift,
                    content: url
                });
            }
        }

        function modify(id) {
            if (isExitsFunction("modifyOverride")) {
                modifyOverride();
            }
            else {

                var url = '@ViewBag.EditView?id=' + id;

                if (isExitsFunction("getModifyViewUrl")) {
                    url = getModifyViewUrl(id);
                }

                layer.open({
                    type: 2,
                    area: ['@ViewBag.EditViewAreaWidth', '@ViewBag.EditViewAreaHeight'],
                    closeBtn: false,
                    title: "",
                    shift: _layerShift,
                    content: url
                });
            }
        }

    </script>

    @RenderSection("script",false)


</head>
<body>
    <div class="header-wrap">
        <div class="header-wrap-inner">
            <div style="float:left;color:white;line-height:35px;font-size:18px;cursor:pointer" onclick="goUrl('/Home/PersonalCenter')">
                 张寿宴玉雕工作室 2.0
            </div>
            <ul class="user-op">
                <li><a href="#">@ViewBag.UserContext.User.name</a><span>|</span></li>
                <li><a href="/Home/Logout">退出</a></li>
            </ul>
        </div>
    </div>
    <div class="header-nav-wrap">
        <div class="header-nav-wrap-inner">
            <ul>
                @if (AuthorizationHelper.Verify("L1_Settings", HttpContext.Current))
                {
                    <li><a href="@Url.Action("User","Settings")" class="@if(ViewBag.MainMenu == "Settings"){@Html.Raw("active")}">系统管理</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Member", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Member", "Member")" class="@if(ViewBag.MainMenu == "Member"){@Html.Raw("active")}">会员管理</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Product", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Product", "Product")" class="@if(ViewBag.MainMenu == "Product"){@Html.Raw("active")}">商品管理</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_MicroClass", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Group","MicroClass")" class="@if(ViewBag.MainMenu == "MicroClass"){@Html.Raw("active")}">课程管理</a></li>
                }      
                <li><a href="@Url.Action("Password","PersonalCenter")" class="@if(ViewBag.MainMenu == "PersonalCenter"){@Html.Raw("active")}">个人中心</a></li>
        
            </ul>
        </div>
    </div>


    <div class="page-container-wrap">
        <div class="page-container-wrap-inner" style="width: 1082px;">
            <div class="nav-wrap">
                @Html.Partial("_LeftMenu")
            </div>
            <div class="main" style="">
               
                <div style="padding:15px 15px 15px 20px;box-sizing:border-box;">
                    <div class="font_black_20" style="float:left;line-height:29px;" id="divTitle">
                        @ViewBag.Title
                    </div>
                    <div style="float:right">
                        @if (String.IsNullOrEmpty(ViewBag.EditView) == false)
                        {
                            <input name="btnCreate" type="button" class="btn_aque" id="btnCreate" value="添加" onclick="create()" />
                        }
                        @RenderSection("buttons", false)
                    </div>
                    <div style="clear:both"></div>
                </div>

                @RenderSection("subTitle", false)
                <div style="height:1px;background-color:#DFDFDF"></div>

                @RenderSection("searchArea", false)

                @RenderSection("afterSearchArea", false)

                <div style="padding:15px;">
                    <table id="table" lay-filter="table"></table>
                </div>


                <div id="divPagingContainer" style="padding-top:20px; padding-bottom:20px;text-align:right; ">
                </div>

            </div>
        </div>
        <div class="footer-wrap">
            <p>张寿宴玉雕工作室</p>
        </div>
    </div>


    @RenderBody()
</body>
</html>

Jade.Shell/Views/Shared/_LayoutWithoutLeftMenu.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @*@Styles.Render("~/Scripts/jqueryui/jquery-ui.css")*@

    @Scripts.Render("~/bundles/common")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/validate/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/layer/layer.js")
    @Scripts.Render("~/Scripts/laytpl.js")
    @Scripts.Render("~/Scripts/laypage/laypage.js")
    @Scripts.Render("~/Scripts/laydate/laydate.js")
    @Scripts.Render("~/Scripts/math.js")
    @*@Scripts.Render("~/Scripts/jqueryui/jquery-ui.js")*@

    @Styles.Render("~/Scripts/layui/css/layui.css")
    @Scripts.Render("~/Scripts/layui/layui.all.js")

    <style>
         body, html {
           background:#E9EBEB;
        }

}
      
    </style>

    <script type="text/javascript">
       
        $(document).ready(function () {
                 
           

        });

    
     

    </script>

</head>
<body>
    <div class="header-wrap">
        <div class="header-wrap-inner">
            <div style="float:left;color:white;line-height:35px;font-size:18px;cursor:pointer" onclick="goUrl('/Home/PersonalCenter')">
                张寿宴玉雕工作室
            </div>
            <ul class="user-op">
                <li><a href="#">@ViewBag.UserContext.User.Name</a><span>|</span></li>
                <li><a href="/Home/Logout">退出</a></li>
            </ul>
        </div>
    </div>
    <div class="header-nav-wrap">
        <div class="header-nav-wrap-inner">
            <ul>
                @if (AuthorizationHelper.Verify("L1_Product", HttpContext.Current))
                {
                    <li><a href="@Url.Action("ProductCenter","Product")" class="@if(ViewBag.MainMenu == "Product"){@Html.Raw("active")}">商品中心</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_ProductPurchase", HttpContext.Current))
                {
                    <li><a href="@Url.Action("ProductPurchase", "ProductPurchase")" class="@if(ViewBag.MainMenu == "ProductPurchase"){@Html.Raw("active")}">采购中心</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Order", HttpContext.Current))
                {
                    <li><a href="@Url.Action("OrderCenter", "Order")" class="@if(ViewBag.MainMenu == "Order"){@Html.Raw("active")}">订单中心</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Storehouse", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Index","Storehouse")" class="@if(ViewBag.MainMenu == "Storehouse"){@Html.Raw("active")}">仓储中心</a></li>
                }

                <li><a href="@Url.Action("BuildingConstraction", "Home")" class="@if(ViewBag.MainMenu == "Home"){@Html.Raw("active")}">包装中心</a></li>

                @if (AuthorizationHelper.Verify("L1_Delivery", HttpContext.Current))
                {
                    <li><a href="@Url.Action("MonthlyOverview", "Delivery")" class="@if(ViewBag.MainMenu == "Delivery"){@Html.Raw("active")}">配送中心</a></li>
                }

                @if (AuthorizationHelper.Verify("L1_Finance", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Overview", "Finance")" class="@if(ViewBag.MainMenu == "Finance"){@Html.Raw("active")}">财务中心</a></li>
                }
                @if (AuthorizationHelper.Verify("L1_DataCenter", HttpContext.Current))
                {
                    <li><a href="@Url.Action("Overview", "DataCenter")" class="@if(ViewBag.MainMenu == "DataCenter"){@Html.Raw("active")}">统计中心</a></li>
                }

                <li><a href="@Url.Action("NewsCatalogView", "News")" class="@if(ViewBag.MainMenu == "News"){@Html.Raw("active")}">新闻中心</a></li>

                <li><a href="@Url.Action("User", "Settings")" class="@if(ViewBag.MainMenu == "Settings"){@Html.Raw("active")}">系统管理</a></li>
            </ul>
        </div>
    </div>


    <div class="page-container-wrap">
        <div class="page-container-wrap-inner" style="width: 1082px;">
           
            <div class="main" style="">

                @RenderBody()

            </div>
        </div>
        <div class="footer-wrap">
            <p>张寿宴玉雕工作室</p>
        </div>
    </div>



</body>
</html>